version: '3.8'

services:
  server:
    image: computer_store_server
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy


  client:
    image: computer_store_client
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_URL: http://server:8080
    depends_on:
      - server


  database:
    image: mysql:5.7
    restart: unless-stopped
    container_name: computer_store_database
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - ./computerstore.sql:/docker-entrypoint-initdb.d/computerstore.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "jan", "-pjanmal" ]
      interval: 30s
      timeout: 10s
      retries: 5

#networks:
 # app-network:
  #      driver: bridge

volumes:
    db-data:
